services:

  auth-server:
    image: auth-server:latest
    build:
      context: auth
      dockerfile: Dockerfile
    expose:
      - 3001
    networks:
      - internal_network
    secrets:
      - jwt_private
      - jwt_public

  front-server:
    image: front-server:latest
    build:
      context: front
      dockerfile: Dockerfile
    expose:
      - 3000
    networks:
      - internal_network

  nginx-server:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
    restart: unless-stopped
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge


secrets:
  jwt_private:
    file: ./secrets/jwt_private.pem

  jwt_public:
    file: ./secrets/jwt_public.pem