events {  }

http {
    log_format main
        '$remote_addr - $remote_user [$time_local] "$request" '
        '$status $body_bytes_sent "$http_referer" '
        '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main;
    error_log /var/log/nginx/error.log debug;

    # hide nginx
    server_tokens off;
    client_max_body_size 16M;
    add_header X-Xss-Protection "1; mode=block" always;
    add_header Referrer-Policy  strict-origin-when-cross-origin;

    upstream front-server {
        server front-server:3000;
    }
    
    upstream auth-server {
        server auth-server:3001;
    }

    server {
        listen 80;

        location ^~ /user/ {
            proxy_pass http://front-server/user/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $http_x_forwarded_for;
        }

        location ^~ /static/ {
            proxy_pass http://front-server/static/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $http_x_forwarded_for;
        }

        location ^~ / {
            auth_request /verify;
            proxy_pass http://front-server;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $http_x_forwarded_for;
        }

        # AUTH SERVER
        
        location = /verify {
            internal;
            proxy_pass http://auth-server/verify;
        }

        location ^~ /auth/ {
            proxy_pass http://auth-server/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $http_x_forwarded_for;
        }
    }
}