events {  }

http {
    log_format main
        '$remote_addr - $remote_user [$time_local] "$request" '
        '$status $body_bytes_sent "$http_referer" '
        '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main;
    error_log /var/log/nginx/error.log debug;

    # hide nginx
    server_tokens off;
    client_max_body_size 16M;
    add_header X-Xss-Protection "1; mode=block" always;
    add_header Referrer-Policy  strict-origin-when-cross-origin;

    upstream front-server {
        server front-server:3000;
    }
    
    upstream auth-server {
        server auth-server:3001;
    }
    
    upstream message-server {
        server message-server:3002;
    }

    server {
        listen 80;

        # MESSAGE SERVER

        location ^~ /message/ {
            set $user_index $http_x_user_index;
            auth_request /verify/hard;
            error_page 401 = @back_to_login;
            auth_request_set $user_id $upstream_http_x_user_id;
            proxy_set_header X-User-Id $user_id;
            proxy_pass http://message-server/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $http_x_forwarded_for;
        }

        # FRONT SERVER

        location ^~ /user/ {
            proxy_pass http://front-server/user/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $http_x_forwarded_for;
        }

        location ^~ /static/ {
            proxy_pass http://front-server/static/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $http_x_forwarded_for;
        }

        location ~ ^/u/([0-9]+)(/.*)?$ {
            set $user_index $1;
            auth_request /verify;
            error_page 401 = @back_to_login;
            # remove /u/{number}/ to forward only the rest
            rewrite ^/u/[0-9]+/?$ / break;
            rewrite ^/u/[0-9]+(/.*)$ $1 break;
            proxy_pass http://front-server;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $http_x_forwarded_for;
        }

        location = / {
            return 302 /user/login;
        }

        # AUTH SERVER
        
        location = /verify/hard {
            internal;
            proxy_pass http://auth-server/verify/hard;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            proxy_set_header X-User-Index $user_index;
        }

        location = /verify {
            internal;
            proxy_pass http://auth-server/verify;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            proxy_set_header X-User-Index $user_index;
        }

        location ^~ /auth/ {
            proxy_pass http://auth-server/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $http_x_forwarded_for;
        }

        # ERROR HANDLING

        location @back_to_login {
            return 302 /user/login;
        }
    }
}